### ISSUE TITLE
"Planet Captured For:"

### ISSUE THREAD

**Issue by Draco18s** [wtzb/SalienProgress#2]
Shouldn't this be "Planet Captured In:"? As in, how long it took to complete?

"Captured For" sounds like a *duration,* i.e. how long ago we captured it (but the capture date is already listed), which does not seem like a useful metric, whereas how *long* it took to capture is a useful metric.

**Comment by wtzb** [comment]
Thanks for your feedback! I completely agree, I've updated it now to reflect 'Captured in' :)
